"""Начало работы над рефакторингом базы данных.

Revision ID: 286ef53ada11
Revises: a9ce856626fb
Create Date: 2026-03-16 23:54:59.680162

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "286ef53ada11"
down_revision: Union[str, Sequence[str], None] = "a9ce856626fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file_shares", "access_level")
    op.add_column(
        "users",
        sa.Column(
            "first_name", sa.String(length=100), nullable=False, server_default=""
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "last_name", sa.String(length=100), nullable=False, server_default=""
        ),
    )
    op.add_column(
        "users",
        sa.Column("username", sa.String(length=100), nullable=False, server_default=""),
    )
    op.add_column(
        "users",
        sa.Column(
            "password_hash", sa.String(length=255), nullable=False, server_default=""
        ),
    )
    op.drop_constraint(op.f("users_name_key"), "users", type_="unique")
    op.create_unique_constraint(None, "users", ["email"])
    op.create_unique_constraint(None, "users", ["username"])
    op.drop_column("users", "name")
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_name_key"), "users", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("users", "password_hash")
    op.drop_column("users", "username")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.add_column(
        "file_shares",
        sa.Column(
            "access_level",
            postgresql.ENUM("READ", "WRITE", "MANAGE", name="accesslevel"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
