"""Создание таблицы для работы временных ссылок на скачивание

Revision ID: 4dc0ee43406d
Revises: cd3b53b4704e
Create Date: 2025-12-29 17:16:13.311861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dc0ee43406d'
down_revision: Union[str, Sequence[str], None] = 'cd3b53b4704e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
