"""Удаление ненужной таблицы BlackList, мелкие правки по таблице share

Revision ID: 83b3fa1f1a70
Revises: 932537fb3ea0
Create Date: 2026-03-23 13:45:17.539535

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "83b3fa1f1a70"
down_revision: Union[str, Sequence[str], None] = "932537fb3ea0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blacklist_tokens_jti"), table_name="blacklist_tokens")
    op.drop_table("blacklist_tokens")
    op.alter_column(
        "share_links", "expires_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "share_links", "max_downloads", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "share_links", "download_count", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "share_links", "download_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "share_links", "max_downloads", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "share_links",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.create_table(
        "blacklist_tokens",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("jti", sa.VARCHAR(length=36), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "token_type", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "revoked_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("reason", sa.TEXT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("blacklist_tokens_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("blacklist_tokens_pkey")),
    )
    op.create_index(
        op.f("ix_blacklist_tokens_jti"), "blacklist_tokens", ["jti"], unique=True
    )
    # ### end Alembic commands ###
