"""Исправление критической ошибки дефолтного значения

Revision ID: b4970d6b477d
Revises: 8a3915e66a3e
Create Date: 2026-03-23 18:21:34.034985

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b4970d6b477d"
down_revision: Union[str, Sequence[str], None] = "8a3915e66a3e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
