"""Создание таблицы для работы временных ссылок на скачивание

Revision ID: cd3b53b4704e
Revises: 72819b5ee6a4
Create Date: 2025-12-29 17:15:24.416566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3b53b4704e'
down_revision: Union[str, Sequence[str], None] = '72819b5ee6a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
