"""Переименование моделей

Revision ID: db4e38efa0bf
Revises: d1042cc6ad79
Create Date: 2026-03-19 21:47:13.192187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4e38efa0bf'
down_revision: Union[str, Sequence[str], None] = 'd1042cc6ad79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('hash_name', sa.String(length=255), nullable=False))
    op.drop_column('files', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('files', 'hash_name')
    # ### end Alembic commands ###
