"""Расширение модели file

Revision ID: fb8bd376d159
Revises: 531bea58967e
Create Date: 2025-12-29 13:16:52.648193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb8bd376d159'
down_revision: Union[str, Sequence[str], None] = '531bea58967e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'files', ['original_filename'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_column('files', 'original_filename')
    # ### end Alembic commands ###
