"""Создание дополнительной таблицы для имплементирования логики общих файлов

Revision ID: 1305bf217ad3
Revises: b38dc8dd09bd
Create Date: 2026-01-04 10:41:05.408707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1305bf217ad3'
down_revision: Union[str, Sequence[str], None] = 'b38dc8dd09bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('shared_at', sa.DateTime(), nullable=False),
    sa.Column('access_level', sa.Enum('READ', 'WRITE', 'MANAGE', name='accesslevel'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('share_links_file_id_fkey'), 'share_links', type_='foreignkey')
    op.create_foreign_key(None, 'share_links', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'share_links', type_='foreignkey')
    op.create_foreign_key(op.f('share_links_file_id_fkey'), 'share_links', 'files', ['file_id'], ['id'])
    op.drop_table('file_shares')
    # ### end Alembic commands ###
