"""Изменение уникальности в полях модели File для устранения ошибки добавления одинаковых файлов 

Revision ID: a9ce856626fb
Revises: 07e88d2ec029
Create Date: 2026-01-04 11:56:25.039321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ce856626fb'
down_revision: Union[str, Sequence[str], None] = '07e88d2ec029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('files_name_key'), 'files', type_='unique')
    op.drop_constraint(op.f('files_original_filename_key'), 'files', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('files_original_filename_key'), 'files', ['original_filename'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('files_name_key'), 'files', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
