name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install linting tools
        run: pip install flake8 black

      - name: Run Black (Check formatting)
        run: black --check . --exclude alembic

      - name: Run Flake8 (Check logic/style)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Compose Alias
        run: sudo ln -s /usr/libexec/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose

      - name: Prepare Files
        run: touch init-db.sql

      - name: Build and Start Infrastructure
        run: |
          make build
          make up
          sleep 30

      - name: Debug DB if failed
        if: failure()
        run: docker logs filecloud_db

      - name: Run Migrations
        run: make migrate

      - name: Run Tests
        run: make test

      - name: Cleanup
        if: always()
        run: make clean
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Install Cloudflare Client
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via Cloudflare Tunnel
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ssh.stadolnik.site
          username: duck
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          proxy_command: /usr/local/bin/cloudflared access ssh --hostname %h

          script: |
            cd /home/duck/Dev/Python/graduation
            git pull origin main
            
            make build
            make up
            make migrate
            
            docker image prune -f