name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install linting tools
        run: pip install flake8 black

      - name: Run Black
        run: black --check . --exclude alembic

      - name: Run Flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Compose Alias
        run: sudo ln -s /usr/libexec/docker/cli-plugins/docker-compose /usr/local/bin/docker-compose

      - name: Build and Start Infrastructure
        run: |
          touch init-db.sql
          make build
          make up
          sleep 20

      - name: Run Migrations and Tests
        run: |
          make migrate
          make test

      - name: Cleanup
        if: always()
        run: make clean

  deploy:
    needs: tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cloudflare Client
        run: |
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

      - name: Deploy via SSH + Cloudflare Tunnel
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ssh.stadolnik.site
          SSH_USER: duck
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_github_actions
          chmod 600 ~/.ssh/id_github_actions

          ssh -T -i ~/.ssh/id_github_actions \
          -o StrictHostKeyChecking=no \
          -o UserKnownHostsFile=/dev/null \
          -o ProxyCommand="/usr/local/bin/cloudflared access ssh --hostname %h" \
          $SSH_USER@$SSH_HOST << 'EOF'
            set -e
            cd /home/duck/Dev/Python/graduation
          
            echo "Updating code..."
            git pull origin main
          
            echo "Rebuilding containers..."
            make build
          
            echo "Restarting services..."
            make up
          
            echo "Waiting for DB to settle..."
            sleep 15
          
            echo "Applying migrations..."
            make migrate
          
            echo "Cleaning up old images..."
            docker image prune -f
          
            echo "Deployment finished successfully!"
          EOF